apiVersion: v1
kind: ConfigMap
metadata:
  name: global
  namespace: default
data:
  environment: ${vpc_name}
  hostname: ${hostname}
  revproxy_arn: ${revproxy_arn}
  dictionary_url: ${dictionary_url}
